# Generated by Django 4.0.4 on 2022-05-26 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sotp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersotp',
            name='otp',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
