# Generated by Django 4.0.4 on 2022-05-26 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sotp', '0002_alter_usersotp_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersotp',
            name='otp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usersotp',
            name='totp',
            field=models.CharField(blank=True, max_length=18, null=True, unique=True),
        ),
    ]
