# Generated by Django 4.0.4 on 2022-05-26 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sotp', '0003_alter_usersotp_otp_alter_usersotp_totp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersotp',
            name='date_modified',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
